import { useLocalSearchParams, router } from 'expo-router';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing, BorderRadius } from '@/constants';
import { Card, PrimaryButton, StateView } from '@/features/passenger-booking/components/BookingUi';
import { useTrip } from '@/features/passenger-booking/hooks/usePassengerBooking';
function duration(from?: string, to?: string) { if (!from || !to) return '—'; const min = Math.max(0, Math.round((+new Date(to) - +new Date(from)) / 60000)); return `${Math.floor(min / 60)}h ${min % 60}m`; }
export default function TripDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const q = useTrip(id); const trip = q.data; const until = trip ? Math.max(0, Math.round((+new Date(trip.departureTime) - Date.now()) / 60000)) : 0; return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Trip details</Text>{q.isLoading ? <StateView title="Loading trip" loading /> : q.isError ? <StateView title="Could not load trip" actionLabel="Retry" onAction={() => void q.refetch()} /> : <><Card><View style={styles.row}><Text style={styles.route}>{trip?.route?.originCity ?? 'Origin'} → {trip?.route?.destinationCity ?? 'Destination'}</Text><Text style={styles.badge}>{trip?.status}</Text></View><Text>Departs {trip?.departureTime ? new Date(trip.departureTime).toLocaleString() : '—'}</Text><Text>ETA {trip?.arrivalEstimate ? new Date(trip.arrivalEstimate).toLocaleString() : '—'}</Text><Text style={styles.countdown}>{until > 0 ? `${until} minutes to departure` : 'Departure time reached'}</Text><Text>Duration {duration(trip?.departureTime, trip?.arrivalEstimate)}</Text></Card><Card><Text style={styles.bold}>Driver & bus</Text><Text>{trip?.driver?.fullName ?? trip?.driver?.name ?? 'Assigned driver'}</Text><Text>{trip?.bus?.model ?? 'Adrash Coach'} · {trip?.bus?.plateNumber ?? 'Plate pending'}</Text><Text>Amenities: {trip?.bus?.amenities?.join(' · ') ?? 'Standard luggage allowance'}</Text></Card><Card><Text style={styles.bold}>Map preview</Text><View style={styles.map}><Text style={styles.mapText}>🗺️ Route polyline preview</Text></View></Card><Card><Text style={styles.bold}>Trip policies</Text>{(trip?.policies ?? ['Arrive 20 minutes before departure.', 'Carry a valid booking reference.', 'Seat locks expire until payment is complete.']).map((p) => <Text key={p}>• {p}</Text>)}</Card><PrimaryButton onPress={() => router.push(`/trip/${id}/tracking`)}>Track live</PrimaryButton></>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, title: { fontSize: 24, fontWeight: '900', color: Colors.text.primary }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.sm }, route: { flex: 1, fontWeight: '900', color: Colors.text.primary, fontSize: 16 }, badge: { color: Colors.semantic.success, fontWeight: '900' }, countdown: { color: Colors.semantic.warning, fontWeight: '900' }, bold: { fontWeight: '900', color: Colors.text.primary }, map: { height: 150, borderRadius: BorderRadius.lg, backgroundColor: Colors.semantic.infoLight, alignItems: 'center', justifyContent: 'center' }, mapText: { color: Colors.semantic.info, fontWeight: '900' } });
