import type React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Colors, BorderRadius, Shadow, Spacing } from '@/constants';
export function StateView({ title, subtitle, actionLabel, onAction, loading }: { title: string; subtitle?: string; actionLabel?: string; onAction?: () => void; loading?: boolean }) { return <View style={styles.state}>{loading ? <ActivityIndicator color={Colors.brand.primary} /> : <Text style={styles.stateEmoji}>🚌</Text>}<Text style={styles.stateTitle}>{title}</Text>{subtitle ? <Text style={styles.stateSub}>{subtitle}</Text> : null}{actionLabel && onAction ? <Pressable style={styles.primaryBtn} onPress={onAction}><Text style={styles.primaryText}>{actionLabel}</Text></Pressable> : null}</View>; }
export function Card({ children }: { children: React.ReactNode }) { return <View style={styles.card}>{children}</View>; }
export function PrimaryButton({ children, onPress, disabled }: { children: React.ReactNode; onPress?: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} style={[styles.primaryBtn, disabled && styles.disabled]} onPress={onPress}><Text style={styles.primaryText}>{children}</Text></Pressable>; }
export function Field({ label, value, onChangeText, placeholder, keyboardType = 'default' }: { label: string; value: string; onChangeText: (v: string) => void; placeholder?: string; keyboardType?: 'default' | 'phone-pad' | 'numeric' }) { return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType} style={styles.input} placeholderTextColor={Colors.text.disabled} /></View>; }
export function Countdown({ expiresAt }: { expiresAt?: string }) { const seconds = expiresAt ? Math.max(0, Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000)) : 0; const m = Math.floor(seconds / 60).toString().padStart(2, '0'); const s = (seconds % 60).toString().padStart(2, '0'); return <Text style={styles.countdown}>Expires in {m}:{s}</Text>; }
const styles = StyleSheet.create({ card: { backgroundColor: Colors.background.primary, borderRadius: BorderRadius.lg, padding: Spacing.md, gap: Spacing.sm, ...Shadow.sm }, state: { alignItems: 'center', justifyContent: 'center', padding: Spacing['2xl'], gap: Spacing.sm }, stateEmoji: { fontSize: 46 }, stateTitle: { fontSize: 18, fontWeight: '800', color: Colors.text.primary, textAlign: 'center' }, stateSub: { color: Colors.text.tertiary, textAlign: 'center' }, primaryBtn: { backgroundColor: Colors.brand.primary, borderRadius: BorderRadius.lg, paddingVertical: 13, paddingHorizontal: Spacing.lg, alignItems: 'center' }, primaryText: { color: '#fff', fontWeight: '800' }, disabled: { opacity: 0.45 }, fieldWrap: { gap: 6 }, label: { color: Colors.text.tertiary, fontWeight: '700', fontSize: 12 }, input: { borderWidth: 1, borderColor: Colors.border.medium, borderRadius: BorderRadius.md, padding: Spacing.md, color: Colors.text.primary, backgroundColor: Colors.background.primary }, countdown: { color: Colors.semantic.warning, fontWeight: '800' } });
