import { useState } from 'react';
import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing } from '@/constants';
import { Card, Field, PrimaryButton } from '@/features/passenger-booking/components/BookingUi';
import { useBookingFlowStore } from '@/features/passenger-booking/store/bookingFlowStore';
import { bookingService } from '@/features/passenger-booking/services/bookingService';
export default function PassengersScreen() { const f = useBookingFlowStore(); const [error, setError] = useState(''); const passengers = f.selectedSeats.map((_seat, i) => f.passengerDetails[i] ?? { fullName: '', phone: '', nextOfKinName: '', nextOfKinPhone: '' }); const update = (i: number, key: keyof typeof passengers[number], value: string) => { const next = [...passengers]; next[i] = { ...next[i], [key]: value }; f.setPassengers(next); }; const next = () => { const bad = passengers.map((p) => bookingService.validatePassenger(p)).find(Boolean); if (bad) setError(bad); else router.push('/(tabs)/booking/summary'); }; return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Passenger details</Text>{passengers.map((p, i) => <Card key={f.selectedSeats[i]}><Text style={styles.cardTitle}>Seat {f.selectedSeats[i]}</Text><Field label="Full name" value={p.fullName} onChangeText={(v) => update(i, 'fullName', v)} /><Field label="Phone" value={p.phone} onChangeText={(v) => update(i, 'phone', v)} keyboardType="phone-pad" placeholder="+2519..." /><Field label="Next of kin name" value={p.nextOfKinName} onChangeText={(v) => update(i, 'nextOfKinName', v)} /><Field label="Next of kin phone" value={p.nextOfKinPhone} onChangeText={(v) => update(i, 'nextOfKinPhone', v)} keyboardType="phone-pad" /></Card>)}{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton onPress={next}>Review booking</PrimaryButton></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, title: { fontSize: 24, fontWeight: '900', color: Colors.text.primary }, cardTitle: { fontWeight: '900', color: Colors.text.primary }, error: { color: Colors.semantic.error, fontWeight: '800' } });
