import { useState } from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing, BorderRadius } from '@/constants';
import { Countdown, Field, PrimaryButton } from '@/features/passenger-booking/components/BookingUi';
import { useInitiatePayment } from '@/features/passenger-booking/hooks/usePassengerBooking';
import { useBookingFlowStore } from '@/features/passenger-booking/store/bookingFlowStore';
import { maskAccountRef, PAYMENT_METHODS } from '@/features/passenger-booking/services/paymentService';
export default function PaymentScreen() { const f = useBookingFlowStore(); const [accountRef, setAccountRef] = useState(f.passengerDetails[0]?.phone ?? ''); const m = useInitiatePayment(); const pay = async () => { if (!f.pendingBooking || !f.selectedPaymentMethod) return; const txn = await m.mutateAsync({ bookingId: f.pendingBooking.id, method: f.selectedPaymentMethod, accountRef }); router.push({ pathname: '/(tabs)/booking/waiting', params: { transactionId: txn.transactionId } }); }; return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Payment</Text>{f.pendingBooking?.expiresAt ? <Countdown expiresAt={f.pendingBooking.expiresAt} /> : null}<Text style={styles.sub}>Choose a payment method. Your account is shown as {maskAccountRef(accountRef)}.</Text>{PAYMENT_METHODS.map((p) => <Pressable key={p} style={[styles.method, f.selectedPaymentMethod === p && styles.active]} onPress={() => f.setPaymentMethod(p)}><Text style={styles.methodText}>{p}</Text></Pressable>)}<Field label="Phone/account reference" value={accountRef} onChangeText={setAccountRef} keyboardType="phone-pad" /><PrimaryButton disabled={!f.selectedPaymentMethod || !accountRef || m.isPending} onPress={() => void pay()}>{m.isPending ? 'Initiating...' : 'Initiate payment'}</PrimaryButton>{m.data?.instructions?.map((i) => <Text key={i} style={styles.sub}>• {i}</Text>)}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, title: { fontSize: 24, fontWeight: '900', color: Colors.text.primary }, sub: { color: Colors.text.tertiary }, method: { backgroundColor: Colors.background.primary, borderRadius: BorderRadius.lg, padding: Spacing.md, borderWidth: 1, borderColor: Colors.border.light }, active: { borderColor: Colors.brand.primary, backgroundColor: Colors.semantic.successLight }, methodText: { fontWeight: '900', color: Colors.text.primary } });
