import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing, BorderRadius } from '@/constants';
import { Card, PrimaryButton, StateView } from '@/features/passenger-booking/components/BookingUi';
import { useRouteBundle } from '@/features/passenger-booking/hooks/usePassengerBooking';
import { useBookingFlowStore } from '@/features/passenger-booking/store/bookingFlowStore';
import { routeService } from '@/features/passenger-booking/services/routeService';
export default function PickupScreen() { const f = useBookingFlowStore(); const q = useRouteBundle(f.selectedRoute?.id); const stops = q.data?.stops ?? []; const dropoffs = stops.filter((s) => s.isDropoff && (!f.selectedPickup || s.sequenceOrder > f.selectedPickup.sequenceOrder)); return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Pickup & dropoff</Text>{q.isLoading ? <StateView title="Loading stops" loading /> : q.isError ? <StateView title="Could not load stops" actionLabel="Retry" onAction={() => void q.refetch()} /> : <><Card><Text style={styles.cardTitle}>Route preview</Text><View style={styles.map}><Text style={styles.mapText}>🗺️ Polyline/map preview</Text></View>{stops.map((s) => <View key={s.id} style={styles.stop}><Text style={styles.marker}>{s.isPickup ? '🟢' : '🔵'}</Text><Text style={styles.stopText}>{s.sequenceOrder}. {s.name}</Text></View>)}</Card><Text style={styles.section}>Select pickup</Text>{(q.data?.pickups ?? []).map((p) => <Pressable key={p.id} style={[styles.option, f.selectedPickup?.id === p.id && styles.active]} onPress={() => f.selectPickup(p)}><Text style={styles.optionTitle}>{p.name}</Text><Text style={styles.optionSub}>{p.description}</Text></Pressable>)}<Text style={styles.section}>Select downstream dropoff</Text>{dropoffs.map((s) => <Pressable key={s.id} style={[styles.option, f.selectedDropoff?.id === s.id && styles.active]} onPress={() => f.selectDropoff(s)}><Text style={styles.optionTitle}>{s.name}</Text><Text style={styles.optionSub}>Stop #{s.sequenceOrder}</Text></Pressable>)}{f.selectedPickup && f.selectedDropoff && !routeService.isDownstream(f.selectedPickup, f.selectedDropoff) ? <Text style={styles.error}>Dropoff must be after pickup.</Text> : null}<PrimaryButton disabled={!routeService.isDownstream(f.selectedPickup, f.selectedDropoff)} onPress={() => { f.setSeats(Array.from({ length: f.passengersCount }, (_, i) => i + 1)); router.push('/(tabs)/booking/passengers'); }}>Continue</PrimaryButton></>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, title: { fontSize: 24, fontWeight: '900', color: Colors.text.primary }, section: { fontWeight: '900', color: Colors.text.primary, marginTop: Spacing.sm }, cardTitle: { fontWeight: '800', color: Colors.text.primary }, map: { height: 140, borderRadius: BorderRadius.lg, backgroundColor: Colors.semantic.infoLight, alignItems: 'center', justifyContent: 'center' }, mapText: { color: Colors.semantic.info, fontWeight: '800' }, stop: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'center' }, marker: { fontSize: 16 }, stopText: { color: Colors.text.secondary }, option: { backgroundColor: Colors.background.primary, borderRadius: BorderRadius.lg, padding: Spacing.md, borderWidth: 1, borderColor: Colors.border.light }, active: { borderColor: Colors.brand.primary, backgroundColor: Colors.semantic.successLight }, optionTitle: { fontWeight: '800', color: Colors.text.primary }, optionSub: { color: Colors.text.tertiary, marginTop: 2 }, error: { color: Colors.semantic.error, fontWeight: '700' } });
