import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing, BorderRadius } from '@/constants';
import { PrimaryButton, StateView } from '@/features/passenger-booking/components/BookingUi';
import { useSeats } from '@/features/passenger-booking/hooks/usePassengerBooking';
import { useBookingFlowStore } from '@/features/passenger-booking/store/bookingFlowStore';
export default function SeatsScreen() { const f = useBookingFlowStore(); const q = useSeats(f.selectedTrip?.id); const seats = q.data ?? []; const toggle = (n: number, booked: boolean) => { if (booked) return; const selected = f.selectedSeats.includes(n); const next = selected ? f.selectedSeats.filter((s) => s !== n) : f.selectedSeats.length >= f.passengersCount ? f.selectedSeats : [...f.selectedSeats, n]; f.setSeats(next); }; return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Choose seats</Text><Text style={styles.sub}>Select {f.passengersCount} seat(s). Seat map refreshes every 30 seconds.</Text>{q.isLoading ? <StateView title="Loading seat map" loading /> : q.isError ? <StateView title="Could not load seats" actionLabel="Retry" onAction={() => void q.refetch()} /> : <View style={styles.bus}>{seats.map((s) => { const sel = f.selectedSeats.includes(s.seatNumber); return <Pressable key={s.seatNumber} style={[styles.seat, s.isBooked && styles.booked, sel && styles.selected]} onPress={() => toggle(s.seatNumber, s.isBooked)}><Text style={[styles.seatText, (sel || s.isBooked) && styles.seatTextActive]}>{s.seatNumber}</Text></Pressable>; })}</View>}<View style={styles.legend}><Text>🟩 Available</Text><Text>🟢 Selected</Text><Text>🟥 Booked</Text></View><PrimaryButton disabled={f.selectedSeats.length !== f.passengersCount} onPress={() => router.push('/(tabs)/booking/passengers')}>Continue</PrimaryButton></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, title: { fontSize: 24, fontWeight: '900', color: Colors.text.primary }, sub: { color: Colors.text.tertiary }, bus: { backgroundColor: Colors.background.primary, borderRadius: BorderRadius['2xl'], padding: Spacing.lg, flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, justifyContent: 'center' }, seat: { width: 54, height: 48, borderRadius: BorderRadius.md, borderWidth: 2, borderColor: Colors.seat.availableBorder, backgroundColor: Colors.seat.available, alignItems: 'center', justifyContent: 'center' }, booked: { backgroundColor: Colors.seat.occupied, borderColor: Colors.seat.occupiedBorder }, selected: { backgroundColor: Colors.seat.selected, borderColor: Colors.seat.selected }, seatText: { color: Colors.text.primary, fontWeight: '900' }, seatTextActive: { color: '#fff' }, legend: { flexDirection: 'row', justifyContent: 'space-around' } });
