import { useState } from 'react';
import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing } from '@/constants';
import { Card, Field, PrimaryButton } from '@/features/passenger-booking/components/BookingUi';
import { useCreateBooking } from '@/features/passenger-booking/hooks/usePassengerBooking';
import { useBookingFlowStore } from '@/features/passenger-booking/store/bookingFlowStore';
import { bookingService } from '@/features/passenger-booking/services/bookingService';
export default function SummaryScreen() { const f = useBookingFlowStore(); const m = useCreateBooking(); const [error, setError] = useState(''); const fare = bookingService.calculateFare(f.selectedSeats.length, f.pointsToRedeem, f.selectedTrip?.fare); const submit = async () => { const body = { tripId: f.selectedTrip?.id ?? '', seatNumbers: f.selectedSeats, pickupLocationId: f.selectedPickup?.id ?? '', dropoffStopId: f.selectedDropoff?.id ?? '', pointsToRedeem: f.pointsToRedeem, passengerDetails: f.passengerDetails }; const bad = bookingService.validateBooking(body, f.selectedPickup, f.selectedDropoff); if (bad) { setError(bad); return; } const booking = await m.mutateAsync(body); f.setPendingBooking(booking); router.push('/(tabs)/booking/payment'); }; return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Checkout</Text><Card><Text style={styles.bold}>{f.origin} → {f.destination}</Text><Text>Seats: {f.selectedSeats.join(', ')}</Text><Text>Pickup: {f.selectedPickup?.name}</Text><Text>Dropoff: {f.selectedDropoff?.name}</Text></Card><Card><Text style={styles.bold}>Fare</Text><Text>Subtotal: ETB {fare.subtotal}</Text><Text>Service fee: ETB {fare.serviceFee}</Text><Text>Rewards: -ETB {fare.rewardsDiscount}</Text><Text style={styles.total}>Total: ETB {fare.total}</Text></Card><Field label="Rewards points to redeem" value={String(f.pointsToRedeem)} onChangeText={(v) => f.setPoints(Math.max(0, Number(v) || 0))} keyboardType="numeric" />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={m.isPending} onPress={() => void submit()}>{m.isPending ? 'Creating booking...' : 'Create booking'}</PrimaryButton></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, title: { fontSize: 24, fontWeight: '900', color: Colors.text.primary }, bold: { fontWeight: '900', color: Colors.text.primary }, total: { fontWeight: '900', color: Colors.brand.primary, fontSize: 18 }, error: { color: Colors.semantic.error, fontWeight: '800' } });
