import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { ScrollView, StyleSheet, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing } from '@/constants';
import { PrimaryButton, StateView } from '@/features/passenger-booking/components/BookingUi';
import { useVerifyPayment } from '@/features/passenger-booking/hooks/usePassengerBooking';
export default function WaitingScreen() { const { transactionId } = useLocalSearchParams<{ transactionId: string }>(); const verify = useVerifyPayment(); const [tries, setTries] = useState(0); useEffect(() => { if (!transactionId || tries >= 30) return; const id = setInterval(() => { setTries((t) => t + 1); verify.mutate(transactionId, { onSuccess: (r) => { if (r.status === 'Success') { clearInterval(id); router.replace('/(tabs)/booking/confirmation'); } } }); }, 4_000); return () => clearInterval(id); }, [transactionId, tries, verify]); const status = verify.data?.status ?? 'Pending'; return <SafeAreaView style={styles.container} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content}><StateView title={status === 'Failed' || status === 'Expired' ? 'Payment failed' : 'Waiting for payment'} subtitle={`Status: ${status}. We poll securely every few seconds.`} loading={status === 'Pending' || status === 'Processing'} />{tries >= 30 ? <Text style={styles.error}>Verification timed out. You can retry.</Text> : null}<PrimaryButton onPress={() => transactionId && verify.mutate(transactionId)}>Verify now</PrimaryButton></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background.secondary }, content: { padding: Spacing.lg, gap: Spacing.md }, error: { color: Colors.semantic.error, fontWeight: '800', textAlign: 'center' } });
