import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { createZustandStorage } from '@/lib/storage';
import type { BookingDTO, PassengerDetailDTO, PaymentMethodDTO, PickupLocationDTO, RouteDTO, SantimPayPartner, StopDTO, TripDTO } from '../dtos/bookingDtos';
interface BookingFlowState { origin: string; destination: string; date: string; time: string; passengersCount: number; recentSearches: Array<{ origin: string; destination: string; date: string; userId?: string }>; selectedRoute: RouteDTO | null; selectedTrip: TripDTO | null; selectedPickup: PickupLocationDTO | null; selectedDropoff: StopDTO | null; selectedSeats: number[]; passengerDetails: PassengerDetailDTO[]; pointsToRedeem: number; pendingBooking: BookingDTO | null; selectedPaymentMethod: PaymentMethodDTO | null; selectedSantimPayPartner: SantimPayPartner | null; setSearch: (p: Partial<Pick<BookingFlowState, 'origin' | 'destination' | 'date' | 'time' | 'passengersCount'>>) => void; swap: () => void; rememberSearch: (userId?: string) => void; selectRoute: (route: RouteDTO | null) => void; selectTrip: (trip: TripDTO | null) => void; selectPickup: (pickup: PickupLocationDTO | null) => void; selectDropoff: (dropoff: StopDTO | null) => void; setSeats: (seats: number[]) => void; setPassengers: (passengers: PassengerDetailDTO[]) => void; setPoints: (points: number) => void; setPendingBooking: (booking: BookingDTO | null) => void; setPaymentMethod: (method: PaymentMethodDTO | null) => void; setSantimPayPartner: (partner: SantimPayPartner | null) => void; resetFlow: () => void; }
function localDateString() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
const initial = { origin: '', destination: '', date: localDateString(), time: '08:00', passengersCount: 1, recentSearches: [], selectedRoute: null, selectedTrip: null, selectedPickup: null, selectedDropoff: null, selectedSeats: [] as number[], passengerDetails: [] as PassengerDetailDTO[], pointsToRedeem: 0, pendingBooking: null, selectedPaymentMethod: null, selectedSantimPayPartner: null };
export const useBookingFlowStore = create<BookingFlowState>()(persist((set, get) => ({ ...initial, setSearch: (p) => set(p), swap: () => set((s) => ({ origin: s.destination, destination: s.origin })), rememberSearch: (userId?: string) => { const { origin, destination, date, recentSearches } = get(); if (!origin || !destination) return; const safe = Array.isArray(recentSearches) ? recentSearches : []; set({ recentSearches: [{ origin, destination, date, ...(userId ? { userId } : {}) }, ...safe.filter((r) => r.origin !== origin || r.destination !== destination)].slice(0, 5) }); }, selectRoute: (selectedRoute) => set({ selectedRoute }), selectTrip: (selectedTrip) => set({ selectedTrip, passengerDetails: [] as PassengerDetailDTO[], selectedSeats: [] as number[], pendingBooking: null, selectedPaymentMethod: null, selectedSantimPayPartner: null, pointsToRedeem: 0 }), selectPickup: (selectedPickup) => set({ selectedPickup }), selectDropoff: (selectedDropoff) => set({ selectedDropoff }), setSeats: (selectedSeats) => set({ selectedSeats }), setPassengers: (passengerDetails) => set({ passengerDetails }), setPoints: (pointsToRedeem) => set({ pointsToRedeem }), setPendingBooking: (pendingBooking) => set({ pendingBooking }), setPaymentMethod: (selectedPaymentMethod) => set({ selectedPaymentMethod }), setSantimPayPartner: (selectedSantimPayPartner) => set({ selectedSantimPayPartner }), resetFlow: () => set(initial) }), {
    name: 'passenger-booking-flow',
    storage: createJSONStorage(() => createZustandStorage('passenger-booking-flow')),
    // Only recentSearches survives a full app kill+relaunch. Everything else
    // (live origin/destination/date/time, selected route/trip/pickup/seats,
    // passenger details, pending booking, payment method) resets to `initial`
    // on every cold start — a killed-and-reopened app has no business showing
    // yesterday's search, a trip that may since be cancelled/completed, or
    // stale passenger PII from an abandoned booking.
    partialize: (s) => ({ recentSearches: s.recentSearches }),
}));
