import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { BookingStatusDTO, CreateBookingDTO, CreateReviewDTO, InitiatePaymentDTO } from '../dtos/bookingDtos';
import { bookingRepository } from '../repositories/bookingRepository';
import { tripRepository, type TripFilters } from '../repositories/tripRepository';
import { routeService } from '../services/routeService';
import { paymentService } from '../services/paymentService';
export const bookingKeys = { routes: ['routes'] as const, routeBundle: (id: string) => ['routes', id, 'bundle'] as const, trips: (f: TripFilters) => ['trips', f] as const, trip: (id: string) => ['trip', id] as const, seats: (id: string) => ['trip', id, 'seats'] as const, bookings: (s: BookingStatusDTO) => ['bookings', s] as const, location: (id: string) => ['trip', id, 'location'] as const };
export function useRoutes() { return useInfiniteQuery({ queryKey: bookingKeys.routes, queryFn: ({ pageParam = 1, signal }) => routeService.listRoutes(pageParam, 20, signal), initialPageParam: 1, getNextPageParam: (last) => last.meta?.totalPages && last.meta.page && last.meta.page < last.meta.totalPages ? last.meta.page + 1 : undefined }); }
export function useRouteBundle(routeId?: string) { return useQuery({ queryKey: bookingKeys.routeBundle(routeId ?? ''), queryFn: ({ signal }) => routeService.getRouteBundle(routeId!, signal), enabled: Boolean(routeId) }); }
export function useTrips(filters: TripFilters) { return useInfiniteQuery({ queryKey: bookingKeys.trips(filters), queryFn: ({ pageParam = 1, signal }) => tripRepository.list({ ...filters, page: pageParam, pageSize: 20 }, signal), initialPageParam: 1, getNextPageParam: (last) => last.meta?.totalPages && last.meta.page && last.meta.page < last.meta.totalPages ? last.meta.page + 1 : undefined }); }
export function useTrip(tripId?: string) { return useQuery({ queryKey: bookingKeys.trip(tripId ?? ''), queryFn: ({ signal }) => tripRepository.detail(tripId!, signal), enabled: Boolean(tripId) }); }
export function useSeats(tripId?: string) { return useQuery({ queryKey: bookingKeys.seats(tripId ?? ''), queryFn: ({ signal }) => tripRepository.seats(tripId!, signal), enabled: Boolean(tripId), refetchInterval: 30_000 }); }
export function useBookings(status: BookingStatusDTO) { return useInfiniteQuery({ queryKey: bookingKeys.bookings(status), queryFn: ({ pageParam = 1, signal }) => bookingRepository.list(status, pageParam, 20, signal), initialPageParam: 1, getNextPageParam: (last) => last.meta?.totalPages && last.meta.page && last.meta.page < last.meta.totalPages ? last.meta.page + 1 : undefined }); }
export function useCreateBooking() { const qc = useQueryClient(); return useMutation({ mutationFn: (body: CreateBookingDTO) => bookingRepository.create(body), onSuccess: () => void qc.invalidateQueries({ queryKey: ['bookings'] }) }); }
export function useInitiatePayment() { return useMutation({ mutationFn: (body: InitiatePaymentDTO) => paymentService.initiate(body) }); }
export function useVerifyPayment() { return useMutation({ mutationFn: (transactionId: string) => paymentService.verify(transactionId) }); }
export function useTripLocation(tripId?: string) { return useQuery({ queryKey: bookingKeys.location(tripId ?? ''), queryFn: ({ signal }) => tripRepository.latestLocation(tripId!, signal), enabled: Boolean(tripId), refetchInterval: 5_000 }); }
export function useSubmitReview() { const qc = useQueryClient(); return useMutation({ mutationFn: (body: CreateReviewDTO) => bookingRepository.review(body), onSuccess: () => void qc.invalidateQueries({ queryKey: ['bookings'] }) }); }
